### ISSUE TITLE
Apply Displacements

### ISSUE THREAD

**Issue by CWillberg** [cmhamel/Exodus.jl#117]
Dear developer,

is there a possibility to store the results such, that the "Apply Displacement" option in Paraview will work?

**Comment by cmhamel** [comment]
@CWillberg in paraview there's a few variable names that will automatically apply displacements when reading the exodus file such "displ" where the components are "displ_x", "displ_y", and "displ_z" in 3D. As long as you do that it should be pretty turn key. Out of curiosity, are you trying to use the apply displacement feature for a non-displacement variable?
