### ISSUE TITLE
Subvariables

### ISSUE THREAD

**Issue by CWillberg** [cmhamel/Exodus.jl#118]
Dear developer,

is there a possibility to store the results such, that the variable is stored in its components?
E.g. Displacements and sublist x,y,z (callable in Paraview via the components)?

**Comment by cmhamel** [comment]
@CWillberg just call your variables displ_x, displ_y, displ_z. Paraview will load this up as a vector and calculate things like vector magnitude for you.

**Comment by CWillberg** [comment]
thanks
