### ISSUE TITLE
Using Exodiff with tolerance file

### ISSUE THREAD

**Issue by JTHesse** [cmhamel/Exodus.jl#140]
I'm interested in leveraging the exodiff function you kindly shared, in conjunction with a tolerance file. 

`exodiff(exofile1,exofile2,tolerance_file)`

I think the exodiff command is structured as follows:

`exodiff -f tolerance.cmd exofile1.e exofile2.e`

I greatly appreciate your assistance with this.

**Comment by cmhamel** [comment]
@JTHesse if you upgrade to Exodus.jl v0.8.2 this capability "should" be functional now. I've tried out a few simple examples and added some unit tests but they don't cover all possibilities in the tolerance command file and I'm sure there's some error handling I haven't covered properly yet. 

The new exodiff method will return true/false for whether the two files are "equal". 

The new syntax is the following

```
exodiff(ex_1, ex_2; component_file=<some_file>)
```
where ```ex_1``` and ```ex_2``` are the paths to your exodus files. 

Let me know if you run into any issues.

**Comment by JTHesse** [comment]
Perfect, exactly what I needed. Thank you!
