### ISSUE TITLE
[Feature]: Allow additional args for exodiff function

### ISSUE THREAD

**Issue by JTHesse** [cmhamel/Exodus.jl#188]
I would like to use the exodiff function with additional arguments.
For example:

`exodiff("file1.e", "file2.e"; args=["-ignore maps","..."])`

This will allow utilizing more functionalities that are provided by exodiff.

**Comment by cmhamel** [comment]
The syntax I added to the referenced PR is the following

```
exodiff("file1.e", "file2.e", ["-Help"])
```
it's almost what you suggested but without the keyword argument.

**Comment by JTHesse** [comment]
Awesome, thank you very much!
