### ISSUE TITLE
Variable names are polluted with extraneous characters while writting values to Exodus files.

### ISSUE THREAD

**Issue by lxmota** [cmhamel/Exodus.jl#202]
In Norma.jl, while calling something like:

`Exodus.write_values(output_mesh, NodalVariable, time_index, "velo_y", velo_y)`

The result is: 
<img width="629" alt="Screenshot 2024-11-22 at 17 32 03" src="https://github.com/user-attachments/assets/43448fb0-97bf-46d0-8158-297e848bb522">

which is confirmed by doing ncdump on the exodus file:

` name_nod_var =
  "disp_x",
  "disp_y",
  "disp_z",
  "refe_x",
  "refe_y",
  "refe_z",
  "velo_x",
  "velo_yh@0\005\243N$\177",
  "velo_z",
  "acce_x",
  "acce_y",
  "acce_z" ;
`

**Comment by cmhamel** [comment]
@lxmota if this is on julia 1.11 I'm aware of the issue and don't have a fix at the moment.

Things are fine on julia 1.10 though.

**Comment by cmhamel** [comment]
Found the issue. It was a two line fix. New release in progress @lxmota. I'll update y'all on the Norma issue since I'm closing this one. New version should be out within the hour.
