### ISSUE TITLE
read_block_names exists but not callable

### ISSUE THREAD

**Issue by lxmota** [cmhamel/Exodus.jl#27]
The function read_block_names is implemented here:

https://github.com/cmhamel/Exodus.jl/blob/master/src/Blocks.jl#L83

but when calling it there is an error:

```
julia> read_block_ids(mesh)
1-element Vector{Int32}:
 1

julia> read_block_names(mesh)
ERROR: UndefVarError: `read_block_names` not defined
Stacktrace:
 [1] top-level scope
   @ REPL[7]:1
```

**Comment by cmhamel** [comment]
For now you can use that method by typing Exodus.read_block_names

I need to add some more methods to the exports of the package.
