### ISSUE TITLE
Undefined types in SideSets.jl

### ISSUE THREAD

**Issue by lxmota** [cmhamel/Exodus.jl#30]
There are undefined variable types in SideSets.jl. They are here:
```
https://github.com/cmhamel/Exodus.jl/blob/master/src/SideSets.jl#L74
https://github.com/cmhamel/Exodus.jl/blob/master/src/SideSets.jl#L75
https://github.com/cmhamel/Exodus.jl/blob/master/src/SideSets.jl#L87
https://github.com/cmhamel/Exodus.jl/blob/master/src/SideSets.jl#L88
```
The type `B` which exist in the `exo` variable is readily available on the first two occurrences above, but not in the last two ones.

This type `B` and the type `I` also from `exo` are used for side sets but not for node sets. Maybe they could be removed?

**Comment by cmhamel** [comment]
@lxmota a fix to this issue was just merged into master.

If you think it's fixed please close the issue.

**Comment by lxmota** [comment]
Fixed. And with this the porting of https://github.com/lxmota/norma is complete!
